interface MenuItem {
  name: string;
  description?: string;
  price: string;
}

interface MenuCategory {
  id: string;
  name: string;
  description: string;
  items: MenuItem[];
}

export const menuData: MenuCategory[] = [
  {
    id: "standard-pizzor",
    name: "Standard Pizzor",
    description: "Klassiska pizzor med traditionella ingredienser och tidlösa smaker",
    items: [
      { name: "Vesuvio", description: "Tomatsås, ost och skinka", price: "125 kr" },
      { name: "Margherita", description: "Tomatsås och ost", price: "120 kr" },
      { name: "Al Tonno", description: "Tomatsås, ost och tonfisk", price: "135 kr" },
      { name: "Riviera", description: "Tomatsås, ost, skinka, champinjoner och räkor", price: "145 kr" },
      { name: "Pollo", description: "Tomatsås, ost, skinka, räkor och ananas", price: "145 kr" },
      { name: "Solemio", description: "Tomatsås, ost, bacon, salami och ägg", price: "145 kr" },
      { name: "Banana", description: "Tomatsås, ost, skinka, banan och curry", price: "135 kr" },
      { name: "Gorgonzola", description: "Tomatsås, ost, skinka, gorgonzola och tomater", price: "145 kr" },
      { name: "Bolognese", description: "Tomatsås, ost, köttfärssås och lök", price: "135 kr" },
      { name: "Supreme", description: "Tomatsås, ost, skinka, räkor, champinjoner, lök och paprika och gratinerad ost", price: "145 kr" },
      { name: "Napoli", description: "Tomatsås, ost, sardeller, oliver och lök", price: "145 kr" },
      { name: "Betty", description: "Tomatsås, ost, fetaost, champinjoner, paprika, purjolök och ruccola", price: "145 kr" },
      { name: "Quattro Stagioni", description: "Tomatsås, ost, skinka, champinjoner, räkor, musslor, oliver och kronärtskocka", price: "145 kr" },
      { name: "Funghi", description: "Tomatsås, ost och champinjoner", price: "125 kr" },
      { name: "Pappas Special", description: "Tomatsås, ost, salami, fetaost, lök, feferoni och tomater", price: "185 kr" },
      { name: "Campagnola", description: "Tomatsås, ost, salami och lök", price: "135 kr" },
      { name: "Bussola", description: "Tomatsås, ost, skinka och räkor", price: "135 kr" },
      { name: "Capricciosa", description: "Tomatsås, ost, skinka och champinjoner", price: "135 kr" },
      { name: "Hawaii", description: "Tomatsås, ost, skinka och ananas", price: "135 kr" },
      { name: "Aroma", description: "Tomatsås, ost, kyckling, paprika och purjolök", price: "195 kr" },
      { name: "Mammas Special", description: "Tomatsås, ost, salami, köttfärs, tomater och lök", price: "145 kr" },
      { name: "Atesh", description: "Tomatsås, ost, köttfärs, lök, tomater, paprika, fetaost och cayennepeppar", price: "145 kr" },
      { name: "Tropicana", description: "Tomatsås, ost, skinka, banan, ananas och curry", price: "135 kr" },
      { name: "Opera", description: "Tomatsås, ost, skinka och tonfisk", price: "135 kr" },
      { name: "Indio", description: "Tomatsås, ost, skinka, ananas, banan, curry, jordnötter och honung", price: "145 kr" },
      { name: "Maestro", description: "Tomatsås, ost, salami, champinjoner, lök, tomater och fetaost", price: "145 kr" },
      { name: "Kycklingpizza", description: "Tomatsås, ost, kyckling, ananas och curry", price: "145 kr" },
      { name: "Pigalle", description: "Tomatsås, ost, champinjoner och räkor", price: "135 kr" },
      { name: "Marinara", description: "Tomatsås, ost, räkor och musslor", price: "135 kr" },
      { name: "Veronica", description: "Tomatsås, ost, peperonikorv, lök och paprika", price: "145 kr" },
      { name: "Seldas", description: "Tomatsås, ost, köttfärs, fetaost, tomater, feferoni och lök", price: "145 kr" },
      { name: "Pompei", description: "Tomatsås, ost, bacon, ägg och lök", price: "135 kr" },
    ],
  },
  {
    id: "mozzarellapizzor",
    name: "Mozzarellapizzor",
    description: "Premiumpizzor med krämig mozzarellaost och utsökta ingredienser",
    items: [
      { name: "Lyckliga Damen", description: "Tomatsås, mozzarellaost, parmesanost, bresaola, purjolök, pinjenötter och ruccola", price: "150 kr" },
      { name: "Parma", description: "Tomatsås, mozzarellaost, parmaskinka och ruccola", price: "145 kr" },
      { name: "Bufala", description: "Tomatsås, mozzarellaost, pepperonikorv, champinjoner, lök och paprika", price: "145 kr" },
      { name: "Ruccola", description: "Tomatsås, mozzarellaost, olivolja och ruccola", price: "135 kr" },
      { name: "Nikolinas", description: "Tomatsås, mozzarellaost, salami, bacon, parmaskinka, mozzarellaost och ruccola", price: "145 kr" },
      { name: "Gambero", description: "Tomatsås, mozzarellaost, räkor, tomater, scampi, persilja, chiliflakes och vitlök", price: "130 kr" },
      { name: "Gastro", description: "Tomatsås, mozzarellaost, fläskfilé, gorgonzola, räkor, champinjoner och tomater", price: "150 kr" },
      { name: "Melanzane", description: "Tomatsås, mozzarellaost, aubergine, spenat, zucchini, champinjoner, parmesanost och ruccola", price: "145 kr" },
      { name: "La Formaggi", description: "Tomatsås, mozzarellaost, gorgonzolaost, fårost och parmesanost", price: "145 kr" },
      { name: "Favoriten", description: "Tomatsås, mozzarellaost, spenat, champinjoner, basilika, parmaskinka och pinjenötter", price: "150 kr" },
      { name: "Romano", description: "Tomatsås, mozzarellaost, chorizokorv, spenat, olivolja och tomater", price: "150 kr" },
      { name: "Mister", description: "Tomatsås, mozzarellaost, chorizokorv, bresaola, parmaskinka, basilika, oliver och soltorkade tomater", price: "150 kr" },
      { name: "Älsklingen", description: "Tomatsås, mozzarellaost, chevréost, parmesan, pinjenötter och honung", price: "150 kr" },
    ],
  },
  {
    id: "mexikanska-pizzor",
    name: "Mexikanska Pizzor",
    description: "Kryddiga pizzor med mexikanska smaker och heta ingredienser",
    items: [
      { name: "Acapulco", description: "Tomatsås, ost, oxfilé, champinjoner, lök, jalapeño, tacosås, tacokrydda och bearnaisesås", price: "195 kr" },
      { name: "Azteka", description: "Tomatsås, ost, skinka, jalapeño, tacosås, tacokrydda och vitlökssås", price: "140 kr" },
      { name: "Nacho", description: "Tomatsås, ost, kyckling, lök, jalapeños, nachochips, tacosås och tacokryddmix", price: "140 kr" },
      { name: "Mexicana", description: "Tomatsås, ost, köttfärs, lök, jalapeño, tacosås och tacokrydda", price: "140 kr" },
    ],
  },
  {
    id: "kebabpizzor",
    name: "Kebabpizzor",
    description: "Pizzor toppade med saftig kebab, grönsaker och smakrika såser",
    items: [
      { name: "Kyckling-Kebabpizza", description: "Tomatsås, ost, kycklingkebab, isbergssallad, tomater, lök, feferoni och vitlökssås", price: "160 kr" },
      { name: "Kebabpizza Special", description: "Tomatsås, ost, kebabkött, isbergssallad, tomater, lök, feferoni, pommes frites och vitlökssås", price: "160 kr" },
      { name: "Gyrospizza", description: "Tomatsås, ost, gyroskött, isbergssallad, tomater, lök, feferoni och vitlökssås", price: "150 kr" },
      { name: "Kebabpizza", description: "Tomatsås, ost, kebabkött, isbergssallad, tomater, lök, feferoni och vitlökssås", price: "150 kr" },
    ],
  },
  {
    id: "skaldjurspizzor",
    name: "Skaldjurspizzor",
    description: "Havets delikatesser med räkor, musslor och färska skaldjur",
    items: [
      { name: "Medelhavet", description: "Tomatsås, ost, tonfisk, räkor, musslor, citron, crabfish och vitlök", price: "150 kr" },
      { name: "Havets Pärlor", description: "Tomatsås, ost, räkor, tonfisk, musslor och scampi", price: "155 kr" },
      { name: "Sevvals", description: "Tomatsås, ost, sardeller, vitlök, musslor, spenat och paprika", price: "150 kr" },
      { name: "Frutti Di Mare", description: "Tomatsås, ost, scampi, räkor, musslor och körsbärstomater", price: "155 kr" },
    ],
  },
  {
    id: "specialpizzor",
    name: "Specialpizzor",
    description: "Våra unika kreationer med premium ingredienser och speciella kombinationer",
    items: [
      { name: "Padre", description: "Tomatsås, ost, fläskfilé, skinka, gorgonzola, vitlök och bearnaisesås", price: "155 kr" },
      { name: "Yusef", description: "Tomatsås, ost, oxfilé, champinjoner, lök, paprika, tomat och bearnaisesås", price: "155 kr" },
      { name: "Oscar", description: "Tomatsås, ost, fläskfilé, champinjoner, lök, paprika och bearnaisesås", price: "155 kr" },
      { name: "Provencale", description: "Tomatsås, ost, fläskfilé, champinjoner, vitlök och bearnaisesås", price: "155 kr" },
      { name: "U-Båt", description: "Tomatsås, ost, oxfilé, champinjoner, vitlök och bearnaisesås", price: "150 kr" },
      { name: "Dennis Special", description: "Tomatsås, ost, salami, bacon, köttfärs, champinjoner, bacon, lök och bearnaisesås", price: "155 kr" },
      { name: "Contezza", description: "Ost, grön pesto, salami, parmesanost, körsbärstomater och spenat", price: "160 kr" },
      { name: "Kärleken", description: "Tomatsås, ost, Chevré, salami, paprika, champinjoner och purjolök", price: "155 kr" },
      { name: "Roma", description: "Tomatsås, ost, oxfilé, champinjoner, lök, gorgonzolaost och tomat", price: "175 kr" },
      { name: "Far & Son", description: "Tomatsås, ost, oxfilé och skinka", price: "155 kr" },
      { name: "Della Casa", description: "Tomatsås, ost, oxfilé, purjolök, körsbärstomater, spenat och bearnaisesås", price: "155 kr" },
      { name: "Hermano", description: "Ost, grön pesto, chevré, parmaskinka, pinjenötter och ruccola", price: "200 kr" },
      { name: "Mafiosa", description: "Tomatsås, ost, salami, pepperonikorv, tomater, färska champinjoner, lök och cayennepeppar", price: "155 kr" },
      { name: "Filé Special", description: "Tomatsås, ost, fläskfilé, oxfilé, champinjoner, lök och bearnaisesås", price: "155 kr" },
      { name: "Me Gusta", description: "Tomatsås, ost, oxfilé, gorgonzola, kantareller och bearnaisesås", price: "160 kr" },
      { name: "Forno", description: "Mozzarellaost, skinka, parmaskinka, soltorkade tomater, rucola", price: "190 kr" },
    ],
  },
  {
    id: "vegetariska-pizzor",
    name: "Vegetariska Pizzor",
    description: "Gröna och färska alternativ helt utan kött",
    items: [
      { name: "Falafelpizza", description: "Tomatsås, ost, falafel, lök, tomater, feferoni, isbergssallad, kebabsås och vitlökssås", price: "180 kr" },
      { name: "Vegetariana", description: "Tomatsås, ost, champinjoner, lök, paprika, oliver och kronärtskocka", price: "175 kr" },
      { name: "Avokadopizza", description: "Tomatsås, ost, soltorkade tomater, ruccola och avokado", price: "175 kr" },
      { name: "Rio", description: "Tomatsås, ost, soltorkade tomater, spenat, paprika, oliver och lök", price: "175 kr" },
      { name: "Benji", description: "Tomatsås, ost, sparris, champinjoner, oliver, lök och majs", price: "175 kr" },
      { name: "Esras", description: "Tomatsås, ost, fetaost, citron, soltorkade tomater, basilika, avokado och oliver", price: "180 kr" },
      { name: "Baran", description: "Tomatsås, ost, champinjoner, tomater, paprika, fetaost och pesto", price: "180 kr" },
    ],
  },
  {
    id: "veganska-pizzor",
    name: "Veganska Pizzor",
    description: "100% växtbaserade pizzor med veganost och fräscha ingredienser",
    items: [
      { name: "Kaktus", description: "Tomatsås, veganost, champinjoner, tomat, lök och paprika", price: "145 kr" },
      { name: "Galetto", description: "Tomatsås, veganost, körsbärstomater, rödlök, paprika och sparris", price: "145 kr" },
      { name: "Vegansk Kebabpizza", description: "Tomatsås, veganost, vegansk kebabkött, lök, tomater, feferoni, kebabsås och vitlökssås", price: "155 kr" },
      { name: "Vegansk Special", description: "Tomatsås, veganost, babyspenat, körsbärstomater, oliver, paprika och broccoli", price: "145 kr" },
      { name: "Paris", description: "Tomatsås, veganost, champinjoner, majs, lök, sparris och oliver", price: "145 kr" },
    ],
  },
  {
    id: "inbakade-pizzor",
    name: "Inbakade Pizzor",
    description: "Calzone och vikta pizzor med generösa fyllningar",
    items: [
      { name: "Dubbel Calzone Special", description: "Tomatsås, ost, skinka, champinjoner och räkor", price: "155 kr" },
      { name: "Tyra", description: "Tomatsås, ost, gyroskött, isbergssallad, tomat, lök, feferoni, kebabsås och vitlökssås", price: "145 kr" },
      { name: "Calzone Special", description: "Tomatsås, ost, skinka, champinjoner och räkor", price: "150 kr" },
      { name: "Idun", description: "Tomatsås, ost, kycklingkebab, isbergssallad, tomater, lök, feferoni, kebabsås och vitlökssås", price: "145 kr" },
      { name: "Viking", description: "Tomatsås, ost, kebabkött, isbergssallad, tomat, lök, feferoni, kebabsås och vitlökssås", price: "145 kr" },
      { name: "Dubbel Calzone", description: "Tomatsås, ost och skinka", price: "135 kr" },
      { name: "Calzone", description: "Tomatsås, ost och skinka", price: "125 kr" },
    ],
  },
  {
    id: "panpizzor",
    name: "Panpizzor",
    description: "Extra tjocka pizzor med mer deg och rikliga pålägg",
    items: [
      { name: "Greeno", description: "Tomatsås, ost, champinjoner, lök, paprika, majs, oliver och tomater", price: "160 kr" },
      { name: "Maderos", description: "Tomatsås, ost, köttfärs, lök, jalapeños, tacosås och tacokrydda", price: "160 kr" },
      { name: "Texas", description: "Tomatsås, ost, salami, champinjoner, lök, tomater och feferoni", price: "160 kr" },
      { name: "Boston", description: "Tomatsås, ost, fläskfilé, gorgonzolaost, champinjoner, oliver, lök och tomater", price: "160 kr" },
      { name: "Crazy Cheese", description: "Tomatsås, ost, mozzarella och cheddar", price: "160 kr" },
      { name: "Arizona", description: "Tomatsås, ost, oxfilé, champinjoner, lök, paprika och bearnaisesås", price: "160 kr" },
      { name: "Honolulu", description: "Tomatsås, ost, skinka, räkor, ananas, banan och curry", price: "160 kr" },
      { name: "Miami", description: "Tomatsås, ost, kyckling, ananas, banan och curry", price: "160 kr" },
      { name: "Kansas", description: "Tomatsås, ost, skinka, bacon, lök, salami, tomater och paprika", price: "160 kr" },
      { name: "Florida", description: "Tomatsås, ost, oxfilé, champinjoner, lök, vitlök, jalapeño, tacosås, tacokryddmix och bearnaisesås", price: "160 kr" },
    ],
  },
  {
    id: "kebabratter",
    name: "Kebabrätter",
    description: "Klassiska kebabrätter med pommes, ris eller i rulleform",
    items: [
      { name: "Kebabtallrik", description: "Kebabkött, lök, isbergssallad, tomater, feferoni, vitlökssås och mild kebabsås. Välj tillbehör", price: "135 kr" },
      { name: "Kycklingkebabtallrik", description: "Kyckling, lök, isbergssallad, tomater, feferoni, vitlökssås och mild kebabsås. Välj tillbehör", price: "150 kr" },
      { name: "Vegansk Kebab med Bröd", description: "Veganskt kebabkött, lök, isbergssallad, tomater, feferoni, vitlökssås och mild kebabsås", price: "130 kr" },
      { name: "Gyrostallrik", description: "Gyroskött, lök, isbergssallad, tomater, feferoni, vitlökssås och mild kebabsås. Välj tillbehör", price: "140 kr" },
      { name: "Mixkebabtallrik", description: "Kebabkött, kyckling, lök, isbergssallad, tomater, feferoni, vitlökssås och kebabsås. Välj tillbehör", price: "160 kr" },
      { name: "Alpha Mixtallrik", description: "Gyroskött, kycklingkebab, kebabkött, lök, isbergssallad, tomater, feferoni, vitlökssås och kebabsås. Välj tillbehör", price: "160 kr" },
      { name: "Kebabrulle", description: "Kebabkött, lök, isbergssallad, tomater, feferoni, vitlökssås och mild kebabsås", price: "135 kr" },
      { name: "Gyrosrulle", description: "Gyroskött, lök, isbergssallad, tomater, feferoni, vitlökssås och mild kebabsås", price: "145 kr" },
      { name: "Falafeltallrik", description: "Falafel, lök, isbergssallad, tomater, feferoni, vitlökssås och mild kebabsås. Välj tillbehör", price: "140 kr" },
      { name: "Gyros med Bröd", description: "Gyroskött, lök, isbergssallad, tomater, feferoni, vitlökssås och mild kebabsås", price: "120 kr" },
      { name: "Vegansk Kebabtallrik", description: "Vegansk kebab, lök, tomat, feferoni, vitlökssås, kebabsås och isbergssallad. Välj tillbehör", price: "150 kr" },
      { name: "Kebab med Bröd", description: "Kebabkött, lök, isbergssallad, tomater, feferoni, vitlökssås och mild kebabsås", price: "110 kr" },
      { name: "Falafelrulle", description: "Falafelbiff, lök, isbergssallad, tomater, feferoni, vitlökssås och vitlökssås", price: "140 kr" },
      { name: "Kyckling-Kebabrulle", description: "Kycklingkebab, lök, isbergssallad, tomater, feferoni, vitlökssås och mild kebabsås", price: "145 kr" },
      { name: "Falafel med Bröd", description: "Falafel, lök, isbergssallad, tomater, feferoni, vitlökssås och mild kebabsås", price: "110 kr" },
      { name: "Vegansk Kebabrulle", description: "Veganskt kebabkött, lök, isbergssallad, tomater, feferoni, vitlökssås och mild kebabsås", price: "150 kr" },
      { name: "Kycklingkebab med Bröd", description: "Kyckling, lök, isbergssallad, tomater, feferoni, vitlökssås och mild kebabsås", price: "110 kr" },
    ],
  },
  {
    id: "hamburgare",
    name: "Hamburgare",
    description: "Saftiga hamburgare med pommes frites och unika kombinationer",
    items: [
      { name: "Halloumiburgare", description: "Friterad halloumi, Crispsallad, lök, tomat, saltgurka, vitlöksdressing", price: "145 kr" },
      { name: "Pepperjackburgare", description: "Pommes frites, lök, isbergssallad, tomater, saltgurka, ketchup, senap, pepperjackost och peppardressing", price: "145 kr" },
      { name: "Manhattan", description: "Pommes frites, högrevsfärs, bacon, krispsallad, rostad lök och chilimajonnäs", price: "145 kr" },
      { name: "Cheeseburgare", description: "Pommes frites, högrevsfärs, cheddarost, mozzarellaost, krispsallad, rostad lök och hamburgardressing", price: "145 kr" },
      { name: "Hamburgare", description: "Pommes frites, lök, isbergssallad, tomater, saltgurka, hamburgerdressing, ketchup och senap", price: "120 kr" },
      { name: "Selles", description: "Pommes frites, högrevsfärs, krispsallad, tomat, saltgurka, rostad lök och srirachamajonnäs", price: "145 kr" },
      { name: "Mexico", description: "Pommes frites, högrevsfärs, jalapeño, rödlök, krispsallad och tryffelmajonnäs", price: "145 kr" },
    ],
  },
  {
    id: "alacarte",
    name: "Á La Carte",
    description: "Alternativa rätter utanför pizzamenyn",
    items: [
      { name: "Kycklingspett", description: "Kyckling, tomater, rödlök, feferoni, isbergssallad, stekta grönsaker, bearnaisesås och vitlökssås", price: "155 kr" },
      { name: "Fish and Chips", description: "Lök, isbergssallad, tomater och remouladsås. Välj tillbehör", price: "145 kr" },
      { name: "Chicken Bits 6 st", description: "Kycklingbitar, lök, isbergssallad, tomater och currydressing. Välj tillbehör", price: "135 kr" },
      { name: "Veggotallrik", description: "Friterad halloumi, falafel, fetaost, isbergssallad, tomater, rödlök, feferoni, ruccola och parmesanost. Välj tillbehör", price: "165 kr" },
    ],
  },
  {
    id: "pastaratter",
    name: "Pastarätter",
    description: "Krämiga och smakrika pastarätter tillagade med färska ingredienser",
    items: [
      { name: "Eiffel Pasta", description: "Körsbärstomater, champinjoner, paprika, lök, chiliflakes, vitlök, persilja och grädde", price: "150 kr" },
      { name: "Oxfilé Pasta", description: "Oxfilé, paprika, champinjoner, lök, gorgonzolaost och grädde", price: "160 kr" },
      { name: "Pesado Pasta", description: "Scampi, musslor, räkor, körsbärstomater, vitlök, chiliflakes och grädde", price: "150 kr" },
      { name: "Carbonara Pasta", description: "Bacon, svartpeppar, lök, äggula och grädde", price: "150 kr" },
      { name: "El Pollo Pasta", description: "Marinerad kycklingfilé, paprika, champinjoner, lök, curry och grädde", price: "150 kr" },
      { name: "Bolognese Pasta", description: "Köttfärs (Nöt), lök, tomatsås, grädde", price: "150 kr" },
    ],
  },
  {
    id: "sallader",
    name: "Sallader",
    description: "Färska och mättande sallader med varierade ingredienser",
    items: [
      { name: "Ost-och skinksallad", description: "Ost, skinka, lök, ägg, paprika, oliver, isbergssallad, tomater, gurka, majs och Rhode Islandsås", price: "135 kr" },
      { name: "Avokadosallad", description: "Isbergssallad, tomat, gurka, majs, avokado, räkor, ruccola, paprika, mozzarella och oliver", price: "135 kr" },
      { name: "Parmasallad", description: "Isbergssallad, tomat, gurka, majs, parmaskinka, oliver, lök, paprika, soltorkade tomater, ruccola", price: "135 kr" },
      { name: "Vegetarisk Sallad", description: "Isbergssallad, tomat, gurka, majs, paprika, lök, citron och oliver", price: "135 kr" },
      { name: "Deluxesallad", description: "Isbergssallad, tomat, gurka, majs, räkor, kyckling, fetaost, paprika, lök, ruccola, avokado och oliver", price: "135 kr" },
      { name: "Tonfisksallad", description: "Tonfisk, ägg, paprika, oliver, isbergssallad, tomater, gurka, majs, citron och Rhode Islandsås", price: "135 kr" },
      { name: "Räksallad", description: "Räkor, ägg, paprika, oliver, isbergssallad, tomater, gurka, majs, citron och Rhode Islandsås", price: "135 kr" },
      { name: "Kebabsallad", description: "Kebabkött, lök, isbergssallad, tomater, feferoni, vitlöksdressing och gurka", price: "135 kr" },
      { name: "Havets Sallad", description: "Isbergssallad, tomat, gurka, majs, tonfisk, oliver, räkor, musslor, paprika, citron och crabfish", price: "135 kr" },
      { name: "Kycklingsallad", description: "Kyckling, ananas, paprika, oliver, isbergssallad, tomater, vitlöksdressing, gurka och majs", price: "135 kr" },
      { name: "Halloumisallad", description: "Friterad halloumiost, lök, majs, avokado, ruccola, tomater, paprika, isbergssallad, gurka och oliver", price: "135 kr" },
      { name: "Grekisksallad", description: "Fetaost, tomater, lök, majs, oliver, fefferon, isbergssallad, gurka", price: "135 kr" },
    ],
  },
  {
    id: "barnratter",
    name: "Barnrätter",
    description: "Perfekt portionerade rätter för våra yngsta gäster",
    items: [
      { name: "Barn chicken bits 4 st", description: "Kycklingbitar, lök, isbergssallad, tomater och currydressing", price: "85 kr" },
      { name: "Hamburgare 45g", description: "Pommes frites, lök, isbergssallad, tomater, saltgurka, hamburgerdressing, ketchup och senap", price: "85 kr" },
    ],
  },
  {
    id: "tillbehor",
    name: "Tillbehör",
    description: "Extra tillbehör och dressingar för att komplettera din måltid",
    items: [
      { name: "Curry dressing", description: "Dressing med smak av curry", price: "20 kr" },
      { name: "Caesardressing", description: "", price: "20 kr" },
      { name: "Falafel styckpris", description: "St", price: "20 kr" },
      { name: "Räksallad", description: "Med blandade grönsaker", price: "20 kr" },
      { name: "Chicken bits styckpris", description: "Friterade kycklingbitar", price: "20 kr" },
      { name: "Lökringar", description: "5 stycken", price: "30 kr" },
      { name: "Remoulad dressing", description: "", price: "20 kr" },
      { name: "Chili Cheese", description: "5 stycken", price: "30 kr" },
      { name: "Rhodeisland dressing", description: "", price: "20 kr" },
      { name: "Vitlöksdressing", description: "Inte vegansk", price: "20 kr" },
      { name: "Pommes frites", description: "Pommes frites", price: "40 kr" },
      { name: "Mozzarella Sticks", description: "5 stycken", price: "30 kr" },
      { name: "Pizzasallad", description: "Vitkålssallad med vinägrette", price: "20 kr" },
      { name: "Vinägrett dressing", description: "", price: "20 kr" },
      { name: "Bearnaisesås", description: "", price: "20 kr" },
      { name: "Halloumi", description: "Halloumiost", price: "20 kr" },
    ],
  },
  {
    id: "efterratter",
    name: "Efterrätter",
    description: "Söta avslutningar för att toppa din måltid",
    items: [
      { name: "Friterad Vetedeg", description: "Med florsocker och sirap", price: "55 kr" },
    ],
  },
  {
    id: "snacks-godis",
    name: "Snacks & Godis",
    description: "Chips, godis och snacks för mellanmål eller att ta med hem",
    items: [
      { name: "Kexchoklad 60g", description: "Kexchoklad innehåller frasiga rån fyllda med choklad under ett täcke av läcker, ljus mjölkchoklad", price: "25 kr" },
      { name: "Gott & Blandat Original 160g", description: "Påsens mix består av populärt vingummi i olika fruktiga smaker, saltlakrits och den kända revolverlakritsen", price: "45 kr" },
      { name: "Ahlgrens Bilar Original 125g", description: "De mjuka bilarna erbjuds här i de klassiska Ahlgrens bilar färgerna rosa, vit och grön", price: "40 kr" },
      { name: "Estrella Sourcream & Onion 275g", description: "Sourcream & onion är en finräfflad klassiker och Sveriges mest populära chips", price: "60 kr" },
      { name: "Estrella Ranch & Sourcream 275g", description: "Finräfflade potatischips med vitlök, tomat, ost, lök-och sourcreamsmak", price: "60 kr" },
      { name: "Estrella Grillchips 275g", description: "Räfflade potatischips med löksmak", price: "60 kr" },
    ],
  },
  {
    id: "ben-jerrys-glass",
    name: "Ben & Jerry's Glass",
    description: "Premium glass från Ben & Jerry's i olika smaker",
    items: [
      { name: "Ben & Jerry's Cookie Dough 465ml", description: "Vaniljgräddglass med kakdeg-och chokladbitar", price: "95 kr" },
      { name: "Ben & Jerry's Half Baked 465ml", description: "Choklad-och vaniljgräddglass med browniebitar och kakdegsbitar med chokladbitar", price: "95 kr" },
      { name: "Ben & Jerry's Chocolate Fudge Brownie 465ml", description: "Chokladgräddglass med bitar av chokladbrownies", price: "95 kr" },
      { name: "Ben & Jerry's Cookie Vermont-ster Sundae 427ml", description: "Gräddglass med chocolate chip cookies och swirls av chokladkakor, toppad med mjukt vispad glass, swirls av choklad med havssalt samt chokladbitar", price: "95 kr" },
      { name: "Ben & Jerry's Caramel Brownie Party 465ml", description: "Kolagräddglass fylld med browniebitar, chokladcookies och salt kolaswirls", price: "95 kr" },
      { name: "Ben & Jerry's Non-Dairy Caramel Café Sundae 427ml", description: "Växtbaserad glass med kola och kaffe, kolakexbitar och marshmallowvirvlar toppad med mjukt vispad växtbaserad glass med kolasåsvirvel och bitar med chokladsmak och havssalt", price: "95 kr" },
      { name: "Ben & Jerry's Dulce De-lish Sundae 100ml", description: "Gräddglass med salt kola, kolabitar & kolavirvlar, toppad med vispad kakaoglass, kolavirvlar och bitar med chokladsmak och havssalt", price: "39 kr" },
      { name: "Ben & Jerry´s Sunny Honey Home 465 ml", description: "Krämig citronglass med swirls av honungskaramell och uppfriskande bitar av citronkakor", price: "95 kr" },
      { name: "Ben & Jerry´s Vanilla Pecan Blondie 465 ml", description: "Krämig vaniljglass med karamelliserade pekannötter, blondie brownies och en salt karamell-swirl", price: "95 kr" },
      { name: "Ben & Jerry's Strawberry Cheesecake 465ml", description: "Gräddglass med jordgubbscheesecake, jordgubbsbitar och en såsvirvel med grahamskex", price: "95 kr" },
    ],
  },
  {
    id: "dryck",
    name: "Dryck",
    description: "Ett brett utbud av läskedrycker och vatten",
    items: [
      { name: "Bonaqua Citron Lime 33 cl", description: "Bonaqua Citron Lime är ett kolsyrat vatten med smak av citron och lime", price: "20 kr" },
      { name: "Champis 33 cl", description: "Champis föddes 1918 och än idag används samma hemliga recept", price: "20 kr" },
      { name: "Coca-Cola Original Taste 2 l", description: "En klassisk favorit för alla tillfällen sedan 1886", price: "50 kr" },
      { name: "Coca-Cola Original Taste 33 cl", description: "Coca-Cola är världens mest välkända och älskade läskedryck", price: "20 kr" },
      { name: "Sprite 33 cl", description: "Sprite är en ikonisk lemon-lime dryck och en av världens mest omtyckta", price: "20 kr" },
      { name: "Coca-Cola Zero 50 cl", description: "Original taste since 1886", price: "30 kr" },
      { name: "Coca-Cola Original Taste 50 cl", description: "Original taste since 1886", price: "30 kr" },
      { name: "Coca-Cola Zero 2 l", description: "Coca-Cola zero sugar är en ny förbättrad sockerfri Coca-Cola", price: "50 kr" },
      { name: "Bonaqua Naturell 33 cl", description: "Bonaqua Naturell är ett kolsyrat svenskt vatten utan tillsatt smak", price: "20 kr" },
      { name: "Fanta Orange 2 l", description: "Fantastisk apelsinsmak", price: "50 kr" },
      { name: "Coca-Cola Zero 33 cl", description: "Snygg favorit, original Cola smak, noll socker", price: "20 kr" },
      { name: "Fanta Orange 33 cl", description: "Fantastisk apelsinsmak", price: "20 kr" },
      { name: "Fanta Exotic 33 cl", description: "Kolsyrad läskedryck med tropisk fruktsmak", price: "20 kr" },
      { name: "Fanta Orange 50 cl", description: "Fanta Orange är en kolsyrad läskedryck med apelsinsmak", price: "30 kr" },
      { name: "Trocadero 33 cl", description: "Dryck med smaken av blandningen apelsin och äpple", price: "20 kr" },
      { name: "MER Jordgubb 20 cl", description: "MER – en svensk fruktdryck med unik smak", price: "15 kr" },
      { name: "MER Apelsin 20 cl", description: "MER – en svensk fruktdryck med unik smak", price: "15 kr" },
    ],
  },
];
